import { build, version as esbuildVersion } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const dependencies = [
    { name: "smol-toml", exports: "parse", file: "smol-toml", license: "LICENSE" },
    { name: "@sinclair/typebox", exports: "Type", file: "typebox", license: "license" },
];

async function packageDirectory(name) {
    let directory = dirname(fileURLToPath(import.meta.resolve(name)));
    while (directory !== dirname(directory)) {
        try {
            const pkg = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
            if (pkg.name === name) return { directory, pkg };
        } catch (error) {
            if (error.code !== "ENOENT") throw error;
        }
        directory = dirname(directory);
    }
    throw new Error(`Could not locate the package metadata for ${name}`);
}

export async function buildVendor({ check = false, outputDirectory = join(root, "vendor") } = {}) {
    const lock = JSON.parse(await readFile(join(root, "package-lock.json"), "utf8"));
    if (lock.packages["node_modules/esbuild"].version !== esbuildVersion)
        throw new Error("The installed esbuild version differs from the plugin lockfile; run npm ci first");
    const files = new Map();
    for (const dependency of dependencies) {
        const { directory, pkg } = await packageDirectory(dependency.name);
        if (lock.packages[`node_modules/${dependency.name}`].version !== pkg.version)
            throw new Error(`${dependency.name} differs from the plugin lockfile; run npm ci first`);
        const licenseFile = `${dependency.file}.LICENSE`;
        const result = await build({
            absWorkingDir: root,
            stdin: { contents: `export { ${dependency.exports} } from ${JSON.stringify(dependency.name)};`, resolveDir: root },
            bundle: true, platform: "node", format: "esm", target: "node24",
            write: false, legalComments: "none",
            banner: { js: `// Generated by scripts/build-vendor.mjs with esbuild ${esbuildVersion}.\n// ${dependency.name}@${pkg.version}; see ${licenseFile}.` },
        });
        // npm workspaces may hoist packages. Keep generated module labels
        // independent of the checkout path and dependency installation layout.
        files.set(`${dependency.file}.mjs`, result.outputFiles[0].text.replace(/^\/\/ .*?node_modules\//gm, "// node_modules/"));
        files.set(licenseFile, (await readFile(join(directory, dependency.license), "utf8"))
            .replace(/\r\n/g, "\n").replace(/[ \t]+$/gm, "").trimEnd() + "\n");
    }
    if (!check) await mkdir(outputDirectory, { recursive: true });
    for (const [name, content] of files) {
        const path = join(outputDirectory, name);
        if (check) {
            const actual = await readFile(path, "utf8").catch(error => {
                if (error.code === "ENOENT") return undefined;
                throw error;
            });
            if (actual !== content)
                throw new Error(`Vendored dependency is missing or stale: ${name}; run npm run build:vendor`);
        } else {
            await writeFile(path, content);
        }
    }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    try {
        if (process.argv.slice(2).some(arg => arg !== "--check"))
            throw new Error("Usage: node scripts/build-vendor.mjs [--check]");
        await buildVendor({ check: process.argv.includes("--check") });
    } catch (error) {
        process.stderr.write(`${error.message}\n`);
        process.exitCode = 1;
    }
}
