// Generate wire DTOs only. Domain conversion belongs to the Rust adapter.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
const schema = JSON.parse(readFileSync(new URL('./schema.json', import.meta.url)));
const pascal = s => s.replace(/(^|_)([a-z])/g, (_, _prefix, letter) => letter.toUpperCase());
const snake = s => s.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
function rust(s) {
    if (s.$ref) return s.$ref.split('/').at(-1);
    if (Array.isArray(s.type)) return `Option<${rust({ ...s, type: s.type.find(t => t !== 'null') })}>`;
    if (s.type === 'array') return `Vec<${rust(s.items)}>`;
    return { string: 'String', integer: s.minimum === 0 ? 'u64' : 'i64', boolean: 'bool', object: 'serde_json::Value' }[s.type] ?? 'serde_json::Value';
}
function ts(s) {
    if (s.$ref) return s.$ref.split('/').at(-1);
    if (s.enum) return s.enum.map(v => JSON.stringify(v)).join(' | ');
    if (Array.isArray(s.type)) return `${ts({ ...s, type: s.type.find(t => t !== 'null') })} | null`;
    if (s.type === 'array') return `Array<${ts(s.items)}>`;
    return { string: 'string', integer: 'number', boolean: 'boolean', object: 'Record<string, unknown>' }[s.type] ?? 'unknown';
}
let rs = '// Generated by plugins/agentix-bridge/protocol/generate.mjs. Do not edit.\n';
rs += `pub const PROTOCOL_VERSION: u64 = ${schema['x-agentix'].version};\npub const MAX_FRAME_BYTES: usize = ${String(schema['x-agentix'].maxFrameBytes).replace(/\B(?=(\d{3})+(?!\d))/g, '_')};\n`;
let types = '// Generated from schema.json. Do not edit.\n';
for (const [name, definition] of Object.entries(schema.$defs)) {
    rs += '#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n';
    if (definition.oneOf) {
        const variants = definition.oneOf.map(v => Object.entries(v.properties)[0]);
        rs += `pub enum ${name} {\n${variants.map(([tag, value]) => `    ${tag}(${rust(value)}),`).join('\n')}\n}\n`;
        types += `export type ${name} = ${variants.map(([tag, value]) => `{ ${tag}: ${ts(value)} }`).join(' | ')};\n`;
        continue;
    }
    if (definition.enum) {
        rs += `pub enum ${name} {\n${definition.enum.map(v => `    #[serde(rename = ${JSON.stringify(v)})]\n    ${pascal(v)},`).join('\n')}\n}\n`;
        types += `export type ${name} = ${ts(definition)};\n`;
        continue;
    }
    rs += `pub struct ${name} {\n`;
    types += `export interface ${name} {\n`;
    for (const [field, value] of Object.entries(definition.properties)) {
        const optional = !definition.required.includes(field);
        if (snake(field) !== field) rs += `    #[serde(rename = ${JSON.stringify(field)})]\n`;
        if (optional) rs += '    #[serde(default)]\n';
        else if (Array.isArray(value.type)) rs += '    #[serde(deserialize_with = "serde::Deserialize::deserialize")]\n';
        rs += `    pub ${snake(field)}: ${optional ? `Option<${rust(value)}>` : rust(value)},\n`;
        types += `    ${field}${optional ? '?' : ''}: ${ts(value)};\n`;
    }
    rs += '}\n'; types += '}\n';
}
// Rustfmt on stdin keeps generation independent of the checkout's current formatting.
rs = execFileSync('rustfmt', ['--emit', 'stdout', '--edition', '2024'], { input: rs, encoding: 'utf8' });
for (const [path, content] of [['../../../crates/agentix-bridge/src/wire.rs', rs], ['./wire.ts', types]]) {
    const file = fileURLToPath(new URL(path, import.meta.url));
    if (process.argv.includes('--check')) {
        if (readFileSync(file, 'utf8') !== content) throw new Error(`Stale generated contract: ${file}`);
    } else writeFileSync(file, content);
}
