import { build } from 'esbuild';
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const target = new URL('./vendor/sdk.mjs', import.meta.url);
const result = await build({ entryPoints: [fileURLToPath(new URL('./sdk.mjs', import.meta.url))], bundle: true,
    platform: 'node', format: 'esm', target: 'node22', minify: true, metafile: true, legalComments: 'inline', write: false });
const output = '// Generated by claude/build.mjs; do not edit. MCP SDK and dependency license notices are included below.\n' + result.outputFiles[0].text.replace(/[ \t]+$/gm, '');
if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== output) throw new Error('Claude SDK bundle is stale; run node claude/build.mjs');
} else writeFileSync(target, output);

const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
    if (!input.includes('node_modules/')) continue;
    let directory = dirname(input);
    while (directory !== dirname(directory)) {
        const manifest = join(directory, 'package.json');
        if (existsSync(manifest)) {
            const pkg = JSON.parse(readFileSync(manifest, 'utf8'));
            if (pkg.name) {
                const license = readdirSync(directory).find(name => /^licen[cs]e(?:\.|$)/i.test(name));
                if (!license) throw new Error(`Missing license for ${pkg.name}`);
                packages.set(pkg.name, `## ${pkg.name} ${pkg.version}\n\n${readFileSync(join(directory, license), 'utf8').trim()}\n`);
                break;
            }
        }
        directory = dirname(directory);
    }
}
const notices = '# Bundled MCP SDK dependency licenses\n\n' + [...packages].sort(([a], [b]) => a.localeCompare(b)).map(([, text]) => text).join('\n');
const licensePath = new URL('./vendor/LICENSES.md', import.meta.url);
if (process.argv.includes('--check')) {
    if (readFileSync(licensePath, 'utf8') !== notices) throw new Error('Claude dependency license notices are stale');
} else writeFileSync(licensePath, notices);
