use crate::Memory;
use anyhow::{Context, Result, ensure};
use serde_json::Value;
const FIELDS: [&str; 10] = [
    "title",
    "conclusion",
    "rationale",
    "scope",
    "conditions",
    "valid_until",
    "tags",
    "kind",
    "evidence",
    "reason",
];
fn header(memory: &Memory) -> Result<Value> {
    let mut value = serde_json::to_value(memory)?;
    let metadata = value.as_object_mut().context("invalid memory metadata")?;
    metadata.remove("content");
    metadata.remove("reason");
    Ok(value)
}
fn start(field: &str) -> String {
    format!("<!-- taskix-memory:{field} -->\n")
}
fn end(field: &str) -> String {
    format!("\n<!-- /taskix-memory:{field} -->")
}
pub(super) fn render(memory: &Memory) -> Result<String> {
    let mut value = serde_json::to_value(&memory.content)?;
    value["reason"] = Value::String(memory.reason.clone());
    let mut result = format!(
        "---\n{}---\n\nRead-only Taskix memory. Do not edit this file in Obsidian. SQLite is authoritative; synchronization replaces local edits. Use taskix memory commands to update memory.\n",
        serde_yaml::to_string(&header(memory)?)?
    );
    result.push_str("\n## content\n");
    for field in FIELDS {
        let text = if let Some(text) = value[field].as_str() {
            text.to_owned()
        } else {
            serde_yaml::to_string(&value[field])?
                .lines()
                .map(|line| format!("    {line}"))
                .collect::<Vec<_>>()
                .join("\n")
        };
        ensure!(
            !text.contains("<!-- taskix-memory:") && !text.contains("<!-- /taskix-memory:"),
            "memory contains reserved document markers"
        );
        let heading = if field == "reason" { "##" } else { "###" };
        result.push_str(&format!(
            "\n{heading} {field}\n\n{}{text}{}\n",
            start(field),
            end(field)
        ));
    }
    Ok(result)
}
