use crate::Memory;
use anyhow::{Context, Result, ensure};
use serde_json::Value;
const FIELDS: [&str; 4] = ["title", "conclusion", "rationale", "scope"];
fn header(memory: &Memory) -> Result<Value> {
    let mut value = serde_json::to_value(memory)?;
    let content = value["content"]
        .as_object_mut()
        .context("invalid memory content")?;
    for field in FIELDS {
        content.remove(field);
    }
    Ok(value)
}
fn start(field: &str) -> String {
    format!("<!-- taskix-memory:{field} -->\n")
}
fn end(field: &str) -> String {
    format!("\n<!-- /taskix-memory:{field} -->")
}
pub(super) fn render(memory: &Memory) -> Result<String> {
    let value = serde_json::to_value(&memory.content)?;
    let mut result = format!(
        "---\n{}---\n\nRead-only Taskix memory. Do not edit this file in Obsidian. SQLite is authoritative; synchronization replaces local edits. Use taskix memory commands to update memory.\n",
        serde_yaml::to_string(&header(memory)?)?
    );
    for field in FIELDS {
        let text = value[field].as_str().context("invalid memory field")?;
        ensure!(
            !text.contains("<!-- taskix-memory:") && !text.contains("<!-- /taskix-memory:"),
            "memory contains reserved document markers"
        );
        result.push_str(&format!(
            "\n## {field}\n\n{}{text}{}\n",
            start(field),
            end(field)
        ));
    }
    Ok(result)
}
