// Generated by plugins/agentix-bridge/protocol/generate.mjs. Do not edit.
pub const PROTOCOL_VERSION: u64 = 2;
pub const MAX_FRAME_BYTES: usize = 8_388_608;
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum SessionStatus {
    #[serde(rename = "notLoaded")]
    NotLoaded,
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "systemError")]
    SystemError,
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "unknown")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum TurnStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "unsupported_method")]
    UnsupportedMethod,
    #[serde(rename = "unsupported_command")]
    UnsupportedCommand,
    #[serde(rename = "busy")]
    Busy,
    #[serde(rename = "delivery_uncertain")]
    DeliveryUncertain,
    #[serde(rename = "host_error")]
    HostError,
    #[serde(rename = "frame_too_large")]
    FrameTooLarge,
    #[serde(rename = "session_changed")]
    SessionChanged,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Session {
    pub id: String,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub name: Option<String>,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub preview: Option<String>,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub cwd: Option<String>,
    #[serde(rename = "updatedAt")]
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub updated_at: Option<i64>,
    pub status: SessionStatus,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Tool {
    pub kind: String,
    pub label: String,
    pub status: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Item {
    pub id: String,
    pub kind: String,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub text: Option<String>,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub status: Option<String>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Turn {
    pub id: String,
    pub status: TurnStatus,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub user_text: Option<String>,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub agent_text: Option<String>,
    pub tools: Vec<Tool>,
    pub items: Vec<Item>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct QueueItem {
    pub id: String,
    pub text: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct QueueState {
    pub items: Vec<QueueItem>,
    pub paused: bool,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub uncertain: Option<serde_json::Value>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Snapshot {
    pub instance: String,
    pub seq: u64,
    pub session: Session,
    pub capabilities: Vec<String>,
    pub turns: Vec<Turn>,
    pub queue: QueueState,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Registration {
    pub version: u64,
    pub agent: String,
    pub instance: String,
    pub pid: u64,
    pub session_id: String,
    pub cwd: String,
    pub session_file: String,
    pub snapshot: SessionInfo,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct History {
    pub turns: Vec<Turn>,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub older_cursor: Option<String>,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub newer_cursor: Option<String>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Prompt {
    pub text: String,
    pub request_id: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PromptResult {
    pub turn_id: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Choice {
    pub label: String,
    pub value: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CommandResult {
    pub body: String,
    pub choices: Vec<Choice>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Request {
    pub id: String,
    pub method: String,
    pub params: serde_json::Value,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Failure {
    pub id: String,
    pub ok: bool,
    pub error: String,
    pub code: ErrorCode,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SessionExited {
    pub session_id: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct QueueChanged {
    pub session_id: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TurnStarted {
    pub session_id: String,
    pub turn_id: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AgentMessageDelta {
    pub session_id: String,
    pub turn_id: String,
    pub item_id: String,
    pub delta: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ItemStarted {
    pub session_id: String,
    pub turn_id: String,
    pub item_id: String,
    pub kind: String,
    pub label: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ItemCompleted {
    pub session_id: String,
    pub turn_id: String,
    pub item: Item,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TurnCompleted {
    pub session_id: String,
    pub turn_id: String,
    pub status: TurnStatus,
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub error: Option<String>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum Event {
    SessionExited(SessionExited),
    QueueChanged(QueueChanged),
    TurnStarted(TurnStarted),
    AgentMessageDelta(AgentMessageDelta),
    ItemStarted(ItemStarted),
    ItemCompleted(ItemCompleted),
    TurnCompleted(TurnCompleted),
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EventFrame {
    pub instance: String,
    pub seq: u64,
    pub event: Event,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SessionInfo {
    pub instance: String,
    pub seq: u64,
    pub session: Session,
    pub capabilities: Vec<String>,
}
